name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-checks-and-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run typecheck
        run: npm run typecheck

      - name: Run code quality checks
        run: npm run check:ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps --only-shell

      - name: Run tests
        run: npm run test
